# Generated by Django 4.1.13 on 2024-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('data_aquisicao', models.DateField()),
                ('custo_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('informacoes_garantia', models.TextField()),
                ('responsavel', models.CharField(max_length=100)),
                ('proxima_manutencao', models.DateField()),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('departamento', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
