# Generated by Django 4.1.13 on 2024-04-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryasset'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='inventory_asset',
        ),
        migrations.AlterModelTable(
            name='inventoryasset',
            table=None,
        ),
    ]
