# Generated by Django 4.1.13 on 2024-04-25 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceschedule_ativo_relacionado_and_more'),
        ('inventory', '0003_alter_asset_table_alter_inventoryasset_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='custo_aquisicao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='data_aquisicao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='fornecedor',
            field=models.CharField(default='Desconhecido', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='informacoes_garantia',
            field=models.TextField(default='Nenhuma'),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='notas',
            field=models.TextField(default='Sem notas'),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='numero_serie',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='proxima_manutencao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='responsavel',
            field=models.CharField(default='Nenhum', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='status',
            field=models.CharField(default='ativo', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryasset',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryasset',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='inventoryasset',
            table='inventory_asset',
        ),
    ]
