# Generated by Django 4.1.13 on 2024-04-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_table_alter_inventoryasset_table'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='ativo_relacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryasset'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ativo_relacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryasset'),
        ),
    ]
